# Start with a Maven base image
FROM maven:3.8.5-openjdk-11 AS build

# Set the working directory inside the container
WORKDIR /app

# Copy the parent pom.xml and module poms
COPY pom.xml .
COPY dao-module/pom.xml ./dao-module/
COPY repo-module/pom.xml ./repo-module/
COPY controller-module/pom.xml ./controller-module/
COPY service-module/pom.xml ./service-module/
COPY util-module/pom.xml ./util-module/
COPY jwt-config/pom.xml ./jwt-config/

# Copy the entire multi-module project into the container
COPY . .


# Download dependencies
RUN mvn dependency:go-offline

# Copy the rest of the project files
COPY . /app

# Build the project
RUN mvn clean package

# Expose the port
EXPOSE 8080

# Run the command
CMD ["mvn", "spring-boot:run"]



