# Start with a Maven base image
FROM maven:3.8.5-openjdk-11 AS build

# Set the working directory inside the container
WORKDIR /app

# Copy the parent pom.xml and module poms
COPY pom.xml .
COPY dao-module/pom.xml ./dao-module/
COPY repo-module/pom.xml ./repo-module/
COPY controller-module/pom.xml ./controller-module/
COPY service-module/pom.xml ./service-module/
COPY util-module/pom.xml ./util-module/
COPY jwt-config/pom.xml ./jwt-config/

# Copy the entire multi-module project into the container
COPY . .

# Build the project (this will create the jar file in target/controller-module)
RUN mvn dependency:go-offline


# Use a smaller image to run the application
FROM openjdk:11-jre-slim

# Set the working directory for the application
WORKDIR /app

# Copy the jar file from the build stage
COPY --from=build /app/controller-module/target/controller-module-0.0.1-SNAPSHOT.jar app.jar

# Expose the application port
EXPOSE 8080

# Define the command to run the application
ENTRYPOINT ["java", "-jar", "app.jar"]
